target-block:
  name: CLAY
ignore:
  enable: true
  blocks:
    - CHEST
    - TRAPPED_CHEST
    - SHULKER_BOX
  ignore-non-solid-tops: true
limits:
  max-radius: 5
  destructive-height: 1
check-frequency: 5
trap-delay: 2
return-delay: 60
check-pitfall-permission: false
enable-item-detection: true
enable-monster-detection: true
ignore-spectators: true
ignore-if-no-destination: true
